M48
; DRILL file {KiCad (6.0.10)} date Tue Jan 31 22:11:16 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-31T22:11:16-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X4.3063Y-5.2587
X4.3063Y-5.3768
T2
X6.7878Y-5.5591
X6.9846Y-5.5591
T0
M30
